---
- hosts: k8s-worker
  remote_user: ec2-user
  become: yes
  gather_facts: no

  tasks:

    - name: Copy the file result_kubeadm_init to workers
      copy:
        src: /apps/terransible/tmp/result_kubeadm_init.txt
        dest: /home/ec2-user/result_kubeadm_init.txt
        owner: ec2-user
        group: ec2-user
        mode: 0644
    
    - name: Grep the kubeadm join to join the worker to the Kubernetes cluster
      command: "grep 'kubeadm join' /home/ec2-user/result_kubeadm_init.txt"
      register: join_command

    - name: Play the command Kubeadm join command
      command: "{{ join_command.stdout_lines[0] }}"
